# Generated by Django 3.0.8 on 2020-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200804_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужской', max_length=10, verbose_name='Пол'),
        ),
    ]
